package com.company.oop.task.management.system.commands.enums;

public enum CommandType {
    ADDCOMMENTTOTASK,
    ADDMEMBERTOTEAM,
    ASSIGNTASK,
    ADDCOMMENT,

    CHANGEPRIORITYOFBUG,
    CHANGEPRIORITYOFSTORY,
    CHANGERATINGOFFEEDBACK,
    CHANGESEVERITYOFBUG,
    CHANGESIZEOFSTORY,
    CHANGESTATUSOFBUG,
    CHANGESTATUSOFFEEDBACK,
    CHANGESTATUSOFSTORY,

    CREATEBOARD,
    CREATEBUG,
    CREATEFEEDBACK,
    CREATEMEMBER,
    CREATETEAM,
    CREATESTORY,

    FILTERTASKSBYASSIGNEE,
    FILTERTASKSBYSTATUS,
    FILTERALLTASKSBYTITLE,

    SHOWALLTASKS,
    SHOWALLTASKSFILTEREDBYTITLE,
    SHOWALLTASKSSORTEBYTITLE,
    SHOWALLTASKSFILTEREDANDSORTEBYTITLE,
    SHOWALLASSIGNEDTASKS,
    SHOWALLASSIGNEDTASKSSORTEBYTITLE,

    SHOWALLBUGS,
    SHOWALLFEEDBACKS,
    SHOWALLSTORIES,

    LOGIN,
    LOGOUT,

    SHOWALLMEMBERS,
    SHOWALLTEAMS,
    SHOWALLTEAMBOARDS,
    SHOWALLTEAMMEMBERS,
    SHOWBOARDACTIVITY,
    SHOWMEMBERACTIVITY,
    SHOWTEAMACTIVITY,

    UNASSIGNTASK,
    HELP
}
