name: Build And Test Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Test My Console Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # Compile the Java application
      - name: Compile the Application
        run: |
          mkdir -p out
          javac -d out $(find ./src -name "*.java")

      # Run the Application (Optional: if you have a main class)
      - name: Run the Application
        run: java -cp out Startup

      # Run JUnit tests
      - name: Run Unit Tests
        run: |
          java -cp "out:lib/*" org.junit.platform.console.ConsoleLauncher \
          --class-path out \
          --scan-class-path \
          --fail-if-no-tests
